valor = float(input("Digite o valor do premio: R$"))
amigo_1 = float(input("Digite a porcentagem que o primeiro amigo investiu: "))
amigo_2 = float(input("Digite a porcentagem que o segundo amigo investiu: "))
amigo_3 = float(input("Digite a porcentagem que o terceiro amigo investiu: "))
premio_1 = valor * (amigo_1/100)
premio_2 = valor * (amigo_2/100)
premio_3 = valor * (amigo_3/100)
print("O valor que o primeiro amigo vai ganhar sera de: R$", premio_1)
print("O valor que o segundo amigo vai ganhar sera de: R$", premio_2)
print("O valor que o terceiro amigo vai ganhar sera de: R$", premio_3)